version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/myfolder/src
    env_file:
      - .env
    ports:
      - 4000:4000

  my-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'diaryjjang'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  my-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.front
    volumes:
      - ../frontend/src:/myfolder/src
      - ../frontend/public:/myfolder/public
    env_file:
      - .env
    ports:
      - 3000:3000

  # my-nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ../frontend/html:/usr/share/nginx/html
  #   ports:
  #     - 80:80